add Helm Chart Document to pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,6 +28,25 @@ jobs:
       - run: yarn update-all-charts
       - run: yarn helm-lint
 
+      - name: Check Helm Chart Document
+        run: |
+          code=0
+          docker run --rm -v "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:v1.5.0 -t ./README.md.gotmpl -o ../../README.md || code=$?;
+          if [ "$code" != "0" ]; then 
+            echo "Failed to run helm-docs!";
+            exit 1;
+          fi;
+          cd deploy
+          code=0
+          git ls-files -m | grep -i readme.md || code=$?;
+          if [ "$code" == "0" ]; then
+            echo -e "Some of helm chart docs are required to be updated using the [helm-docs](https://github.com/norwoodj/helm-docs) tool. \n
+            Please run helm-docs (v1.5.0) at project root, review & commit docs changes and push a new commit.";
+            exit 1;
+          else 
+            echo -e "helm docs check passed. helm docs update is not required.";
+          fi;
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
 
